parameters:
  keyboardman_filemanager.token.enabled: "%env(bool:FILEMANAGER_TOKEN_ENABLED)%"
  keyboardman_filemanager.tokens: "%env(json:file:resolve:FILEMANAGER_TOKENS)%"

services:
  _defaults:
    autoconfigure: true
    autowire: true

  Keyboardman\FilemanagerBundle\Controller\:
    resource: "../src/Controller/"
    tags: ["controller.service_arguments"]

  Keyboardman\FilemanagerBundle\Form\Type\:
    resource: "../src/Form/Type/"
    tags: ["form.type"]
    public: true

  Keyboardman\FilemanagerBundle\Security\IframeTokenValidator:
    arguments:
      $verify: "%keyboardman_filemanager.token.enabled%"
      $hostTokens: "%keyboardman_filemanager.tokens%"

  Keyboardman\FilemanagerBundle\DTO\QueryFilterFactory:
    public: true

  Keyboardman\FilemanagerBundle\Disk\DiskManager:
    arguments:
      $disks: !tagged_iterator
        tag: keyboardman_filemanager.disk

  Keyboardman\FilemanagerBundle\Upload\:
    resource: "../src/Upload/"

  Keyboardman\FilemanagerBundle\Media\Streaming\:
    resource: "../src/Media/Streaming/"

  Keyboardman\FilemanagerBundle\Media\Streaming\MediaRangeReaderResolver:
    arguments:
      $readers:
        - '@Keyboardman\FilemanagerBundle\Media\Streaming\AsyncAwsS3MediaRangeReader'
        - '@Keyboardman\FilemanagerBundle\Media\Streaming\LocalMediaRangeReader'
        - '@Keyboardman\FilemanagerBundle\Media\Streaming\FallbackMediaRangeReader'

  Keyboardman\FilemanagerBundle\Controller\FilemanagerController:
    bind:
      $chunkSize: "%keyboardman_filemanager.upload.chunk_size%"
      $chunkThreshold: "%keyboardman_filemanager.upload.chunk_threshold%"

  Keyboardman\FilemanagerBundle\Twig\FilemanagerExtension:
    public: true
    tags: ["twig.extension"]
